config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  
  resources :products do
    resources :orders
  end
  

  
  get "users/sign_up"
  get "users/sign_in"
  
  
  get 'pages/about'
  get 'pages/contact'
  
  get 'product' => "products#index"
  
  get 'seller' => "products#seller"

  root "pages#welcome"
end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :address, :city, :county, :postcode, :country, :phone, presence: true
  
  belongs_to :product
  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates_presence_of :image
  
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  
  belongs_to :user
  has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :username, presence: true
  
  has_many :products, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @product = Product.find(params[:product_id])
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @product = Product.find(params[:product_id])
    @seller = @product.user
    
    @order.product_id = @product.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :county, :postcode, :country, :phone)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  def seller
    @products = Product.where(user: current_user).order("created_at DESC")
  end
  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("created_at DESC")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
    
    def check_user
      if current_user != @product.user
        redirect_to root_url, alert: "Sorry, this item is not belongs to you"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
  
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class= "alert alert-danger alert-dismissable"> 
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>#{sentence}</h4>
      <ul>#{messages}</ul>
    </div>
    HTML
    
    html.html_safe
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer">
	 <h5 class="copyright">&copy; MarketSecondHand; 2017; ArtusBayDesign.</h5>
	 <nav>
	     <a href="https://www.facebook.com/artoriusXIII" target="_blank"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
	     <a href="https://www.linkedin.com/in/arturjanka?trk=nav_responsive_tab_profile_pic" target="_blank"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
	     
	 </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="masthead" class="logo-top">
		<div class="mid-content clearfix">
  		<div id="site-logo">
    		<div class="jumbotron1">
    		  <h1>Marketbag Here We are!!!  </h1>
    		  <h2>Access to many fantastic second hand items</h2>
        </div>
		  </div>
		</div>
</header>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Marketbox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About", pages_about_path %></li>
          <li><%= link_to "Product", products_path %></li>
          <li><%= link_to "Contact", pages_contact_path %></li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Manage Products", seller_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketbag</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  
  
  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Cabin" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  


  
</head>
</head>
<body>
  
  <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |name, msg|  %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
              <button type="buton" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        <% end %>
        
      <%= yield %>
    </div>
    
   <%= render 'layouts/footer' %>
  
</body>
</html>

app/views/orders/_form.html.erb
<div class="container-fluid">
 <div class="row">
 
              <div class="panel-heading">
                  <h2 align="center">Create New Order</h2>
              </div>
    <div class="panel-body">
            <%= form_for([@product, @order]) do |f| %>
            
              <% if @order.errors.any? %>
                <div id="error_explanation" class= "alert alert-danger alert-dismissable"> 
                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <h4><%= pluralize(@order.errors.count, "error") %> prohibited this product from being saved:</h4>
            
                  <ul>
                    <% @order.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
      
          <div class="col-sm-12">
          <div class="form-group">
            
              <%= f.label :address %><br>
              <%= f.text_field :address, placeholder: "Address", class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="form-group">
              <%= f.label :city %><br>
              <%= f.text_field :city, placeholder: "City/Town", class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="form-group">
              <%= f.label :county %><br>
              <%= f.text_field :county, placeholder: "County", class: "form-control" %>
            </div>
          </div>
          <div class="col-sm-4">
              <div class="form-group">
              <%= f.label :postcode %><br>
              <%= f.text_field :postcode, placeholder: "Postcode / Zipcode", class: "form-control" %>
            </div>
          </div>
          
          <div class="col-sm-8">
            <div class="form-group">
              <%= f.label :country %><br>
              <%= f.country_select :country, { priority_countries: ["IE","GB", "FR", "DE"]}, class: "form-control" %>
            </div>
          </div>
          </br>
          <div class="col-sm-12">
            <div class="form-group">
              <%= f.label :phone %><br>
              <%= f.text_field :phone, placeholder: "Phone number", class: "form-control" %>
            </div>
          </div>
          
          <div class="center">
            <div class="form-group">
              <%= f.submit "Complete Order", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
    </div>
  </div>  
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>County</th>
      <th>Postcode</th>
      <th>Country</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.address %></td>
        <td><%= order.city %></td>
        <td><%= order.county %></td>
        <td><%= order.postcode %></td>
        <td><%= order.country %></td>
        <td><%= order.phone %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
   <div class="panel panel-default">
     
        <%= render 'form' %>
        <div class="center">
            <div class="form-group">
              <%= link_to 'Back', product_orders_path, class: "btn btn-primary btn-outline btn-sm" %>
            </div>
          </div>
        
    
   </div>

app/views/orders/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>County:</strong>
  <%= @order.county %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @order.postcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @order.country %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.phone %>
</p>




<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
      <div class="jumbotron-about">
          <div class="container-fluid">
                <h1 class="text-left">Website Under Construction!</h1>
                <h2 class="text-left">I am working hard to make it happened!</h2>
                <h2 class="text-left">Stay Tuned!</h2>
               
          </div>
      </div>

app/views/pages/contact.html.erb
<div class="jumbotron-contact">
    <div class="container-fluid">
          <h1 class="text-left">Website Under Construction!</h1>
          <h2 class="text-left">I am working hard to make it happened!</h2>
          <h2 class="text-left">Stay Tuned!</h2>
         
    </div>
</div>

app/views/pages/welcome.html.erb
        <div class="jumbotron">
          <div class="container-fluid">
                <h1 class="text-left">Sell your old stuff here!</h1>
                <h2 class="text-left">Value For Money</h2>
                <h2 class="text-left">Variety</h2>
                <p><a class="btn btn-primary btn-lg" href="/products" role="button">Learn more &raquo;</a></p>
          </div>
        </div>

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:multipart => true }) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation" class= "alert alert-danger alert-dismissable"> 
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-grou">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-grou">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product, class: "btn btn-link" %> |
<%= link_to 'Back', products_path, class: "btn btn-linkdefault" %>

app/views/products/index.html.erb
<div class="center-products">
  <h1>Listing Products</h1>
</div>
<hr>
<div class="right">
  <%= link_to 'Add a new product', new_product_path, class: "btn btn-secondary btn-lg active" %>
</div>
</br>
<div class="center">
  <div class="row">
    <% @products.each do |product| %>
        <div class="col-md-3">
          <div class="thumbnail">
            <%= link_to image_tag(product.image.medium.url), product %>
            <div class="caption">
              <h3><%= product.name %></h3>
              <p><%= number_to_currency(product.price, :unit => "€") %></p>
              <p><%="Sold by #{product.user.username}" %></p>
                <%= link_to 'Edit', edit_product_path(product), class: "btn btn-primary" %>
                <%= link_to 'Remove', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<!--<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= image_tag(product.image.medium.url) %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->

<br>

app/views/products/new.html.erb
<h1>New Product</h1>





      <%= render 'form' %> 
 
      <%= link_to 'Back', products_path, class: "btn btn-primary" %>

app/views/products/seller.html.erb
<div class="right">
  <%= link_to 'Add a new product', new_product_path, class: "btn btn-secondary btn-lg active" %>
</div>
</br>

<table class="table table-striped table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Description</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody class="tbody-color">
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= link_to image_tag(product.image.url), product %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn active dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit', edit_product_path(product), class: "btn btn-default btn-sm" %></li>
              <li><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</hr>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @product.image.large.url %>
    </div>
  </div>

  <div class="col-md-6">
    <h3><%= @product.name %></h3>
    <h4><%= number_to_currency(@product.price, :unit => "€") %></h4>
    <p><%= @product.description %></p>
      <%= link_to 'Buy It Now', new_product_order_path(@product), class: "btn btn-primary btn-outline" %>
  </div>
</div>  

<%= link_to 'Edit', edit_product_path(@product), class: "btn btn-info" %> |
<%= link_to 'Back', products_path, class: "btn btn-info" %>